grails-app/taglib/au/org/ala/bie/BieTagLib.groovy

https://github.com/AtlasOfLivingAustralia/bie-index/issues/64

Show accepted name for synonyms

---

grails-app/views/species/show.gsp
web-app/css/species.css
web-app/js/species.show.js

adds indigenous tab, which pulls data from ALA Profiles collections that are tagged as 'IEK' collections.

https://github.com/AtlasOfLivingAustralia/profile-hub/issues/358 

---

grails-app/i18n/messages.properties

https://github.com/AtlasOfLivingAustralia/bie-index/issues/123

Fix spelling of miscellaneous literature

---

build.gradle

From https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_grails_publish.gradle without web component

publish with ALA publication template

---

.travis.yml

When will he realise that he has no hope against the Illuminati and their nefarious plans to sabotage the build?

Look! It's another pathetic attempt to get the bie-plugin to publish.

---

grails-app/assets/stylesheets/atlas.css
grails-app/i18n/messages.properties
grails-app/views/species/_names.gsp

Also, fix to configuration for altered bq= and hl= config.

Add multiple entry taxonRemarks and provenance

---

build.gradle
grails-app/assets/javascripts/charts.js
grails-app/assets/javascripts/jquery.i18n.properties.js
grails-app/assets/stylesheets/charts.css
grails-app/controllers/au/org/ala/bie/I18nMessagesController.groovy
grails-app/controllers/au/org/ala/bie/UrlMappings.groovy
grails-app/views/species/show.gsp

Update charts configuration for charts plugin
Include jquery.i18n.properties libraries (use specific versio, since latest version has problems)
Provide messages for jquery.i128n.properties

Release 1.4.2

---

grails-app/views/species/search.gsp

Fixes pagination to pass correct no. of rows and sort field into page links

Fix pagination options

---

grails-app/assets/javascripts/species.show.js
grails-app/conf/plugin.yml
grails-app/controllers/au/org/ala/bie/ExternalSiteController.groovy

See https://discuss.eol.org/t/eol-data-services/236 Text sources are still being migrated, the filter_by_string is a bug.

Update for changes to EoL API

---

grails-app/assets/javascripts/species.show.js
grails-app/conf/plugin.yml
grails-app/controllers/au/org/ala/bie/ExternalSiteController.groovy
grails-app/views/species/_classification.gsp

See https://discuss.eol.org/t/eol-data-services/236

Handle changes to EoL API

---

build.gradle
grails-app/assets/javascripts/species.show.js

Allow use of preferred images not connected to occurrence records

Remove logging conflict from ala-name-matching import

---

.travis.yml
build.gradle
grails-app/assets/javascripts/species.show.js
grails-app/assets/stylesheets/show.css
grails-app/assets/stylesheets/species.css
grails-app/conf/application.yml
grails-app/conf/plugin.yml
grails-app/controllers/au/org/ala/bie/ExternalSiteController.groovy
grails-app/i18n/messages.properties
grails-app/services/au/org/ala/bie/ExternalSiteService.groovy
grails-app/views/externalSite/_bhl.gsp
grails-app/views/externalSite/bhl.gsp
grails-app/views/species/_literature.gsp
grails-app/views/species/_names.gsp
grails-app/views/species/search.gsp
grails-app/views/species/show.gsp
src/test/groovy/au/org/ala/bie/ExternalSiteServiceSpec.groovy
src/test/resources/au/org/ala/bie/bhl-search-1.json
src/test/resources/au/org/ala/bie/test.yml

Pull literature data from the BHL and show it in a formatted form.
Minor driver-by bug fixes, including the error caused by taxonRemarks in a synonym.

Get literature data from the Biodiversity Heritage Library

---

grails-app/taglib/au/org/ala/bie/BieTagLib.groovy

Bug introduced by incorrect URL processing.

Correct language codes config processing

---

.travis.yml
grails-app/views/species/_literature.gsp

And make both BHL and trove links configurable as God intended.
Fix for https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/176

Fix incorrect BHL link.

---

grails-app/conf/application.yml
grails-app/i18n/messages.properties
grails-app/views/species/search.gsp

Remove hard-coded message in search webpage
Make record a species URL more configurable.

Adjustments for iNaturalist

---

build.gradle
grails-app/assets/javascripts/atlas.js
grails-app/services/au/org/ala/bie/BieService.groovy
grails-app/services/au/org/ala/bie/BiocacheService.groovy
grails-app/services/au/org/ala/bie/UtilityService.groovy
grails-app/services/au/org/ala/bie/WebClientService.groovy
grails-app/views/species/show.gsp

See https://github.com/AtlasOfLivingAustralia/bie-index/issues/262
Change webService to webClientService to avoid collision with other w…ebService
Include family in preferred image naming
Include different auth-plugin and images-client-plugin

Fixes for preferred image problems

---

build.gradle
grails-app/assets/javascripts/atlas.js
grails-app/services/au/org/ala/bie/BieService.groovy
grails-app/services/au/org/ala/bie/BiocacheService.groovy
grails-app/services/au/org/ala/bie/UtilityService.groovy
grails-app/services/au/org/ala/bie/WebClientService.groovy
grails-app/views/species/show.gsp

Integration with new authentication and image client libarary to allow prefer image to aoccur properly.

Version 1.4.20

---

build.gradle
grails-app/views/species/_overview.gsp
grails-app/views/species/search.gsp

And include updated translations

Remove NPE from dud entries

---

build.gradle
grails-app/services/au/org/ala/bie/ExternalSiteService.groovy
grails-app/views/species/_literature.gsp
grails-app/views/species/show.gsp

Created for ala-bie 1.4.24
Uses consistent synonym list

Release 1.4.24

---

grails-app/init/bie/plugin/BootStrap.groovy
src/main/groovy/au/org/ala/bie/BiePluginGrailsPlugin.groovy

Use of external resources packaged by:
https://github.com/living-atlases/ala-i18n
Other [similar PRs](https://github.com/search?q=is%3Apr+author%3Avjrj+org%3AAtlasOfLivingAustralia+ala-i18n+external&type=Issues).

Usage of external ala-i18n resources

---

grails-app/views/species/search.gsp

Improve presentation of items like web pages with link identifiers as well as guids
